<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ceylon</string>
	</array>
	<key>name</key>
	<string>Ceylon</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#module</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#package</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#imports</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#code</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>annotations</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#ceylondoc</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>match</key>
									<string>abstract</string>
									<key>name</key>
									<string>storage.modifier.abstract.ceylon</string>
								</dict>
								<dict>
									<key>match</key>
									<string>actual</string>
									<key>name</key>
									<string>storage.modifier.actual.ceylon</string>
								</dict>
								<dict>
									<key>match</key>
									<string>default</string>
									<key>name</key>
									<string>storage.modifier.default.ceylon</string>
								</dict>
								<dict>
									<key>match</key>
									<string>formal</string>
									<key>name</key>
									<string>storage.modifier.formal.ceylon</string>
								</dict>
								<dict>
									<key>match</key>
									<string>final</string>
									<key>name</key>
									<string>storage.modifier.final.ceylon</string>
								</dict>
								<dict>
									<key>match</key>
									<string>late</string>
									<key>name</key>
									<string>storage.modifier.formal.ceylon</string>
								</dict>
								<dict>
									<key>match</key>
									<string>sealed</string>
									<key>name</key>
									<string>storage.modifier.sealed.ceylon</string>
								</dict>
								<dict>
									<key>match</key>
									<string>shared</string>
									<key>name</key>
									<string>storage.modifier.shared.ceylon</string>
								</dict>
								<dict>
									<key>match</key>
									<string>\w+</string>
									<key>name</key>
									<string>storage.modifier.ceylon</string>
								</dict>
							</array>
						</dict>
					</dict>
					<key>contentName</key>
					<string>storage.type.annotation.ceylon</string>
					<key>match</key>
					<string>\b(abstract|actual|annotation|default|formal|final|late|optional|sealed|shared|variable)\s+</string>
					<key>name</key>
					<string>meta.declaration.annotation.language.ceylon</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\b(deprecated|by|native|license|tagged)\s*(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.ceylon</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.annotation-arguments.begin.ceylon</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>storage.type.annotation.ceylon</string>
					<key>end</key>
					<string>(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.annotation-arguments.end.ceylon</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.declaration.annotation.language.ceylon</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#strings</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\b(doc)\s*(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.ceylon</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.annotation-arguments.begin.ceylon</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.annotation-arguments.end.ceylon</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.declaration.annotation.language.ceylon</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#ceylondoc</string>
						</dict>
					</array>
				</dict>
			</array>
			<key>repository</key>
			<dict>
				<key>ceylondoc</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>^\s*("(?:"")?)</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.comment.begin.ceylondoc</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(\1)\s*$</string>
							<key>endCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.comment.end.ceylondoc</string>
								</dict>
							</dict>
							<key>name</key>
							<string>comment.block.documentation.ceylon</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<key>class-body</key>
		<dict/>
		<key>code</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#annotations</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#interfaces</string>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.ceylon</string>
						</dict>
					</dict>
					<key>match</key>
					<string>/\*\*/</string>
					<key>name</key>
					<string>comment.block.empty.ceylon</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments-inline</string>
				</dict>
			</array>
		</dict>
		<key>comments-inline</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(//)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.ceylon</string>
						</dict>
					</dict>
					<key>name</key>
					<string>comment.line.double-slash.ceylon</string>
					<key>while</key>
					<string>^\s*(//)</string>
					<key>whileCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.ceylon</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>imports</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\b(import)\s+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.import.ceylon</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?&lt;=[\n;])</string>
					<key>name</key>
					<string>meta.import.ceylon</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>match</key>
							<string>([^\s{;.]+)\s*</string>
							<key>name</key>
							<string>variable.other.package.ceylon</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>{</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>meta.bracket.ceylon</string>
								</dict>
							</dict>
							<key>end</key>
							<string>}</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>meta.bracket.ceylon</string>
								</dict>
							</dict>
							<key>name</key>
							<string>meta.import.selector.ceylon</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>captures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>variable.other.import.alias.ceylon</string>
										</dict>
										<key>2</key>
										<dict>
											<key>name</key>
											<string>keyword.operator.ceylon</string>
										</dict>
										<key>3</key>
										<dict>
											<key>name</key>
											<string>variable.other.import.ceylon</string>
										</dict>
									</dict>
									<key>match</key>
									<string>(?x) \s*
									([^\s.,}]+) \s*
									(=) \s*
									([^\s.,}]+) \s</string>
								</dict>
								<dict>
									<key>match</key>
									<string>([^\s.,}]+)</string>
									<key>name</key>
									<string>variable.other.import.ceylon</string>
								</dict>
								<dict>
									<key>match</key>
									<string>\.\.\.</string>
									<key>name</key>
									<string>keyword.operator.import.wildcard.ceylon</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>interfaces</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?=\w?[\w\s]*(?:interface|dynamic)\s+(?:(?:\\[iI])?\w+))</string>
					<key>end</key>
					<string>}</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.class.end.ceylon</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.interface.ceylon</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#annotations</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>\b(interface|dynamic)\s+((?:\\[iI])?\w+)</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.other.interface.ceylon</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>entity.name.type.interface.ceylon</string>
									<key>patterns</key>
									<array>
										<dict>
											<key>match</key>
											<string>\b([:lower:]|\\i)(?=\w*)</string>
											<key>name</key>
											<string>invalid.illegal.lowercase_character_not_allowed_here.ceylon</string>
										</dict>
									</array>
								</dict>
							</dict>
							<key>end</key>
							<string>(?=\{|of|extends|satisfies|given)</string>
							<key>name</key>
							<string>meta.definition.interface.identifier.ceylon</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>\b(of)\s+</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.other.of.ceylon</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?=\{|extends|satisfies|given)</string>
							<key>name</key>
							<string>meta.definition.case.enumeration.ceylon</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>captures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>constant.character.escape.initial-uppercase.ceylon</string>
										</dict>
										<key>2</key>
										<dict>
											<key>name</key>
											<string>entity.other.case-class.ceylon</string>
										</dict>
									</dict>
									<key>match</key>
									<string>(\\I)([\w_]+)\s*</string>
									<key>name</key>
									<string>meta.other.case-class.ceylon</string>
								</dict>
								<dict>
									<key>captures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>entity.other.case-class.ceylon</string>
										</dict>
									</dict>
									<key>match</key>
									<string>\b([[:upper:]][\w_]*)\s*</string>
									<key>name</key>
									<string>meta.other.case-class.ceylon</string>
								</dict>
								<dict>
									<key>captures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>constant.character.escape.initial-lowercase.ceylon</string>
										</dict>
										<key>2</key>
										<dict>
											<key>name</key>
											<string>entity.other.case-value.ceylon</string>
										</dict>
									</dict>
									<key>match</key>
									<string>(\\i)([\w_]+)\s*</string>
									<key>name</key>
									<string>meta.other.case-value.ceylon</string>
								</dict>
								<dict>
									<key>captures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>entity.other.case-value.ceylon</string>
										</dict>
									</dict>
									<key>match</key>
									<string>\b([[:lower:]][\w_]*)\s*</string>
									<key>name</key>
									<string>meta.other.case-value.ceylon</string>
								</dict>
								<dict>
									<key>match</key>
									<string>\|{1}(?=\s*[\\\w_])</string>
									<key>name</key>
									<string>keyword.operator.type.union.ceylon</string>
								</dict>
								<dict>
									<key>match</key>
									<string>[^\s]</string>
									<key>name</key>
									<string>invalid.illegal.character_not_allowed.ceylon</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>\b(satisfies)\s+</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.other.satisfies.ceylon</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?:\{|given)</string>
							<key>name</key>
							<string>meta.definition.interface.satisfies.ceylon</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>match</key>
									<string>\|{1}</string>
									<key>name</key>
									<string>keyword.operator.type.union.ceylon</string>
								</dict>
								<dict>
									<key>match</key>
									<string>&amp;{1}</string>
									<key>name</key>
									<string>keyword.operator.type.intersection.ceylon</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#type-specifier</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>{</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.section.class.begin.ceylon</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?=})</string>
							<key>name</key>
							<string>meta.interface.body.ceylon</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#class-body</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
			</array>
			<key>repository</key>
			<dict>
				<key>keyword-given</key>
				<dict>
					<key>patterns</key>
					<array/>
				</dict>
				<key>keyword-of</key>
				<dict>
					<key>patterns</key>
					<array/>
				</dict>
				<key>keyword-satisfies</key>
				<dict>
					<key>patterns</key>
					<array/>
				</dict>
			</dict>
		</dict>
		<key>module</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#annotations</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\b(module)\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.module.ceylon</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?&lt;=[\n;])</string>
					<key>name</key>
					<string>meta.module.ceylon</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>variable.other.module.ceylon</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>string.other.module.version.ceylon</string>
								</dict>
							</dict>
							<key>match</key>
							<string>([^\s;"{]+)\s*("[^"]+")\s*</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>{</string>
							<key>end</key>
							<string>}</string>
							<key>name</key>
							<string>meta.module.body.ceylon</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#annotations</string>
								</dict>
								<dict>
									<key>captures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>keyword.other.import.ceylon</string>
										</dict>
										<key>2</key>
										<dict>
											<key>name</key>
											<string>variable.other.import.module.ceylon</string>
										</dict>
										<key>3</key>
										<dict>
											<key>name</key>
											<string>string.other.maven.module.ceylon</string>
										</dict>
										<key>4</key>
										<dict>
											<key>name</key>
											<string>string.other.module.import.version.ceylon</string>
										</dict>
										<key>5</key>
										<dict>
											<key>name</key>
											<string>punctuation.terminator.ceylon</string>
										</dict>
									</dict>
									<key>contentName</key>
									<string>storage.modifier.import.ceylon</string>
									<key>match</key>
									<string>\b(import)\b\s*((?:[^\s;"]+)|("[^"]+"))\s*("[^"]+")\s*(;)</string>
									<key>name</key>
									<string>meta.module.import.ceylon</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>package</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.package.ceylon</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other.package.ceylon</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.terminator.ceylon</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(package)\b(?:\s*([^ ;$]+)\s*(;))</string>
					<key>name</key>
					<string>meta.package.ceylon</string>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.ceylon</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.ceylon</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.ceylon</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#character-escapes</string>
						</dict>
					</array>
				</dict>
			</array>
			<key>repository</key>
			<dict>
				<key>character-escapes</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\[btnfre\\"'`0]</string>
							<key>name</key>
							<string>constant.character.escape.ceylon</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>\\(?=\{)</string>
							<key>end</key>
							<string>(?&lt;=\})</string>
							<key>name</key>
							<string>constant.character.escape.ceylon</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>match</key>
									<string>\{#\h{2,6}\}</string>
									<key>name</key>
									<string>constant.character.escape.unicode.code.ceylon</string>
								</dict>
								<dict>
									<key>match</key>
									<string>\{(?:[A-Z](?:[A-Z0-9\-]*?[A-Z0-9])?)(?: (?:[A-Z](?:[A-Z0-9\-]*?[A-Z0-9])?))*\}</string>
									<key>name</key>
									<string>constant.character.escape.unicode.name.ceylon</string>
								</dict>
								<dict>
									<key>match</key>
									<string>\{[^\}]*\}</string>
									<key>name</key>
									<string>invalid.illegal.unknown-escape.ceylon</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>invalid.illegal.unknown-escape.ceylon</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<key>type-name</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>pattern</string>
					<key>name</key>
					<string>(\\I)</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.ceylon</string>
	<key>uuid</key>
	<string>15C8CAE9-7CF9-4373-ACDE-1B8810171251</string>
</dict>
</plist>
